=== jmccrae/wn-rdf/WN-LMF-simple.dtd
<?xml version='1.0' encoding="UTF-8"?>
<!ELEMENT LexicalResource (Lexicon+)>
<!ELEMENT Lexicon (LexicalEntry+, Synset*)>
<!ATTLIST Lexicon
label CDATA #IMPLIED
language CDATA #REQUIRED>
<!ELEMENT LexicalEntry (Lemma, Sense*)>
<!ATTLIST LexicalEntry
id ID #IMPLIED>
<!ELEMENT Lemma EMPTY>
<!ATTLIST Lemma
writtenForm CDATA #REQUIRED
partOfSpeech CDATA #REQUIRED>
<!ELEMENT Sense (SenseAxis*)>
<!ATTLIST Sense
id ID #REQUIRED
synset IDREF #REQUIRED>
<!ELEMENT Synset (Definition?, SynsetRelation*)>
<!ATTLIST Synset
id ID #REQUIRED
ili CDATA #REQUIRED>
<!ELEMENT Definition (Statement*)>
<!ATTLIST Definition
gloss CDATA #REQUIRED>
<!ELEMENT Statement EMPTY>
<!ATTLIST Statement
example CDATA #REQUIRED>
<!ELEMENT SynsetRelation EMPTY>
<!ATTLIST SynsetRelation
target IDREF #REQUIRED
relType CDATA #REQUIRED>
<!ELEMENT SenseAxis EMPTY>
<!ATTLIST SenseAxis
target IDREF #REQUIRED
relType CDATA #REQUIRED>

=== jmccrae/wn-rdf/example-simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LexicalResource SYSTEM "WN-LMF-simple.dtd">
<LexicalResource>
    <Lexicon label="Princeton WordNet" language="eng">
        <LexicalEntry id="w1">
            <Lemma writtenForm="entity" partOfSpeech="n"/>
            <Sense id="pwn-100001740-n-1" synset="pwn-100001740-n"/>
        </LexicalEntry>
        <LexicalEntry id="w2">
            <Lemma writtenForm="able" partOfSpeech="a"/>
            <Sense id="pwn-300001740-a-1" synset="pwn-300001740-a">
                <SenseAxis relType="antonym" target="pwn-300002908-a-1"/>
            </Sense>
        </LexicalEntry>
        <Synset id="pwn-100001740-n" ili="s35545">
            <Definition gloss="that which is perceived or known or inferred to have its own distinct existence (living or nonliving)"/>
            <SynsetRelation relType="hyponym" target="pwn-104431553-n"/>
            <SynsetRelation relType="hyponym" target="pwn-100002137-n"/>
            <SynsetRelation relType="hyponym" target="pwn-100001930-n"/>
        </Synset>
        <Synset id="pwn-100001740-a-1" ili="s1">
            <Definition gloss="(usually followed by `to') having the necessary means or skill or know-how or authority to do something"/>
            <SynsetRelation relType="attribute" target="pwn-105624029-n"/>
            <SynsetRelation relType="attribute" target="pwn-105204437-n"/>
        </Synset>
    </Lexicon>
</LexicalResource>
