=== jmccrae/wn-rdf/WN-LMF.dtd
<?xml version='1.0' encoding="UTF-8"?>
<!ELEMENT LexicalResource (GlobalInformation, Lexicon+, SenseAxes?)>
<!ELEMENT GlobalInformation EMPTY>
<!ATTLIST GlobalInformation 
label CDATA #IMPLIED>
<!ELEMENT Lexicon (LexicalEntry+, Synset*)>
<!ATTLIST Lexicon
languageCoding CDATA #FIXED "ISO 639-3"
label CDATA #IMPLIED
language CDATA #REQUIRED
owner CDATA #REQUIRED
version CDATA #REQUIRED>
<!ELEMENT LexicalEntry (Meta?, Lemma, Sense*)>
<!ATTLIST LexicalEntry
id ID #IMPLIED>
<!ELEMENT Lemma EMPTY>
<!ATTLIST Lemma
writtenForm CDATA #REQUIRED
partOfSpeech CDATA #REQUIRED>
<!ELEMENT Sense (Meta?, MonolingualExternalRefs?)>
<!ATTLIST Sense
id ID #REQUIRED
synset IDREF #REQUIRED>
<!ELEMENT Meta EMPTY>
<!ATTLIST Meta
author CDATA #IMPLIED
date CDATA #IMPLIED
source CDATA #IMPLIED
status CDATA #IMPLIED
confidenceScore CDATA #IMPLIED>
<!ELEMENT Synset (Meta?, Definition?, SynsetRelations, MonolingualExternalRefs)>
<!ATTLIST Synset
id ID #REQUIRED
baseConcept (1|2|3) #REQUIRED>
<!ELEMENT Definition (Statement*)>
<!ATTLIST Definition
gloss CDATA #REQUIRED>
<!ELEMENT Statement EMPTY>
<!ATTLIST Statement
example CDATA #REQUIRED>
<!ELEMENT SynsetRelations (SynsetRelation+)>
<!ELEMENT SynsetRelation (Meta?)>
<!ATTLIST SynsetRelation
target IDREF #REQUIRED
relType CDATA #REQUIRED>
<!ELEMENT MonolingualExternalRefs (MonolingualExternalRef+)>
<!ELEMENT MonolingualExternalRef (Meta?)>
<!ATTLIST MonolingualExternalRef 
externalSystem CDATA #REQUIRED
externalReference CDATA #REQUIRED
relType (at|plus|equal) #IMPLIED>
<!ELEMENT SenseAxes (SenseAxis+)>
<!ELEMENT SenseAxis (Meta?, Target+, InterlingualExternalRefs?)>
<!ATTLIST SenseAxis
id ID #REQUIRED
relType CDATA #REQUIRED>
<!ELEMENT Target EMPTY>
<!ATTLIST Target
ID CDATA #REQUIRED>
<!ELEMENT InterlingualExternalRefs (InterlingualExternalRef+)>
<!ELEMENT InterlingualExternalRef (Meta?)>
<!ATTLIST InterlingualExternalRef 
externalSystem CDATA #REQUIRED
externalReference CDATA #REQUIRED
relType (at|plus|equal) #IMPLIED>

=== jmccrae/wn-rdf/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LexicalResource SYSTEM "WN-LMF.dtd">
<LexicalResource>
    <GlobalInformation label="Princeton WordNet 3.1"/>
    <Lexicon languageCoding="ISO 639-3" label="Princeton WordNet" language="eng" owner="Princeton" version="3.1">
        <LexicalEntry id="w1">
            <Lemma writtenForm="entity" partOfSpeech="n"/>
            <Sense id="pwn-100001740-n-1" synset="pwn-100001740-n"/>
        </LexicalEntry>
        <LexicalEntry id="w2">
            <Lemma writtenForm="able" partOfSpeech="a"/>
            <Sense id="pwn-300001740-a-1" synset="pwn-300001740-a"/>
        </LexicalEntry>
        <Synset id="pwn-100001740-n" baseConcept="1">
            <Definition gloss="that which is perceived or known or inferred to have its own distinct existence (living or nonliving)"/>
            <SynsetRelations>
                <SynsetRelation relType="hyponym" target="pwn-104431553-n"/>
                <SynsetRelation relType="hyponym" target="pwn-100002137-n"/>
                <SynsetRelation relType="hyponym" target="pwn-100001930-n"/>
            </SynsetRelations>
            <MonolingualExternalRefs>
                <MonolingualExternalRef externalReference="s35545" externalSystem="ili"/>
            </MonolingualExternalRefs>
        </Synset>
        <Synset id="pwn-100001740-a-1" baseConcept="2">
            <Definition gloss="(usually followed by `to') having the necessary means or skill or know-how or authority to do something"/>
            <SynsetRelations>
                <SynsetRelation relType="attribute" target="pwn-105624029-n"/>
                <SynsetRelation relType="attribute" target="pwn-105204437-n"/>
            </SynsetRelations>
            <MonolingualExternalRefs>
                <MonolingualExternalRef externalReference="s1" externalSystem="ili"/>
            </MonolingualExternalRefs>
        </Synset>
    </Lexicon>
    <SenseAxes>
        <SenseAxis id="axis1" relType="antonym">
            <Target ID="pwn-300001740-a-1"/>
            <Target ID="pwn-300002908-a-1"/>
        </SenseAxis>
    </SenseAxes>
</LexicalResource>
